[package]
name = "zed_beancount"
version = "0.2.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/beancount.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.6.0"
