id = "beancount"
name = "Beancount"
description = "Beancount support."
version = "0.0.5"
schema_version = 1
authors = ["Max Brunsfeld <max@zed.dev>", "Marshall Bowers <marshall@zed.dev>"]
repository = "https://github.com/zed-extensions/beancount"

[grammars.beancount]
repository = "https://github.com/polarmutex/tree-sitter-beancount"
commit = "b7a2557e6c8cf1dc70a52cece1861522ad3903fc"

[language_servers.beancount]
name = "Beancount LSP"
language = "Beancount"
