id = "beancount"
name = "Beancount"
description = "Beancount support with syntax highlighting, language server integration, and IDE features."
version = "0.2.0"
schema_version = 1
authors = ["Brian Ryall <brian@brianryall.xyz>"]
repository = "https://github.com/polarmutex/zed-beancount"

[grammars.beancount]
repository = "https://github.com/polarmutex/tree-sitter-beancount"
commit = "b7a2557e6c8cf1dc70a52cece1861522ad3903fc"

[language_servers.beancount-language-server]
name = "beancount-language-server"
language = "Beancount"
