name = "Beancount"
grammar = "beancount"
path_suffixes = ["beancount", "bean"]
line_comments = ["; "]
# autoclose_before = ";:.,=}])"

brackets = [{ start = "\"", end = "\"", close = false, newline = false }]
# brackets = [
#     { start = "{", end = "}", close = true, newline = true },
#     { start = "[", end = "]", close = true, newline = true },
#     { start = "(", end = ")", close = true, newline = true },
#     { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
# ]

# auto_pairs = [
#     { start = "\"", end = "\"" },
#     { start = "(", end = ")" },
#     { start = "[", end = "]" },
#     { start = "{", end = "}" }
# ]

# word_characters = ["_", "-", ":"]
# tab_size = 2
# hard_tabs = false

# language_servers = ["beancount-language-server"]

# [formatter.external]
# command = "bean-format"
# arguments = ["--align-posting", "--currency-column=60"]
